name: 🗣️ Generate and Deploy Vocabulary Audio

on:
  push:
    branches:
      - master
    paths:
      - 'lists/**.json'

jobs:
  generate-audio-files:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests boto3
          
      - name: Generate and Upload Audio
        run: python generate_and_upload.py
        env:
          UNREAL_SPEECH_API_KEY: ${{ secrets.UNREAL_SPEECH_API_KEY }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          R2_BUCKET: ${{ secrets.R2_BUCKET }}
          R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}

      - name: Commit updated processed words list
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add lists/available_vocab.json
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Chore: Update processed vocabulary list 🤖"
            git push
          fi
